POST http://localhost:3000/products/seed
Content-Type: application/json

{
    "quantity": 200
}
###
GET http://localhost:3000/products?limit=2
###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name":"Syltherine",
    "sku":"GYB06",
    "category": 7, 
"description":"Stylish cafe chair",
"large_description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eget mi euismod, bibendum erat vel, tempor lectus. Donec aliquam justo sed lorem tempor, vel fermentum urna posuere. Nullam at augue at quam varius aliquet in a arcu.",
"price": 2500000,
"discount_price": 3500000,
"discount_percent": 30,
"is_new": false,
"image_link":"https://i.postimg.cc/Qtc09hjv/mesa.png"

}
###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name":"Leviosa",
    "sku":"1283A",
    "category": 8, 
"description":"Stylish cafe chair",
"large_description":"Curabitur ultricies risus et lacus pharetra, non volutpat mi luctus. Cras ac odio nec mauris mollis bibendum. Integer efficitur ante non odio interdum, sit amet finibus ex aliquet. Aenean eu purus euismod, gravida purus vel, gravida libero.",
"price":2500000,
"is_new": false,
"image_link":"https://i.postimg.cc/sDmH4j5r/cadeira.png"

}
###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name":"Lolito",
    "sku":"SSD09",
    "category": 9, 
"description":"Luxury big sofa",
"large_description":"Nulla facilisi. Phasellus maximus felis vel nibh euismod, ut fermentum ligula iaculis. Quisque ut velit at urna bibendum faucibus a eget sapien. Suspendisse potenti. Morbi accumsan felis id lorem iaculis tincidunt. Donec viverra eros sed metus tincidunt.",
"price": 7000000,
"discount_price": 1400000,
"discount_percent": 50,
"is_new": false,
"image_link":"https://i.postimg.cc/kGcsss6c/sofa-grande.png"

}

###

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Respira",
    "sku": "MC001",
    "category": 7, 
    "description": "Outdoor bar table and stool",
    "large_description": "Nam sollicitudin, erat sed vulputate feugiat, urna velit scelerisque purus, sed aliquet libero erat nec ex. Mauris non lorem in eros mollis sollicitudin. Proin tempor mi at tellus tincidunt scelerisque. Curabitur dictum purus ac nisi venenatis tempus.",
    "price": 500000,
    "is_new": true,
    "image_link": "https://i.postimg.cc/y8WjhFVm/sofa-sala.png"
}

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Grifo",
    "sku": "CG202",
    "category": 8, 
    "description": "Night lamp",
    "large_description": "Sed non leo ac lorem vestibulum pretium. Integer consequat turpis ac nunc iaculis tincidunt. Fusce viverra neque nec velit varius fringilla. Ut feugiat tortor ut ligula ultricies bibendum. Duis consectetur orci quis augue eleifend, sed facilisis magna.",
    "price": 1500000,
    "is_new": false,
    "image_link": "https://i.postimg.cc/RV4bt66d/abajur.png"
}

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Muggo",
    "sku": "LM303",
    "category": 9, 
    "description": "Small mug",
    "large_description": "Morbi malesuada leo nec lectus fringilla, at cursus dolor tristique. Nam id est et tortor tempus consequat. Donec quis arcu auctor, cursus libero a, bibendum eros. Etiam interdum ligula vel orci malesuada, a accumsan ante hendrerit. Curabitur non massa.",
    "price": 150000,
    "is_new": true,
    "image_link": "https://i.postimg.cc/Z5gcwCR1/sofa.png"
}


###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Pingky",
    "sku": "EL404",
    "category": 8, 
    "description": "Cute bed set",
    "large_description": "Aliquam in est ut ipsum faucibus facilisis. Nulla facilisi. Etiam ac turpis a erat aliquet scelerisque. Fusce bibendum dui a massa vestibulum, in convallis purus tristique. Suspendisse ornare nunc eget orci tempor varius. Cras volutpat tellus sit amet.",
    "price": 7000000,
    "discount_price": 14000000,
    "discount_percent": 50,
    "is_new": false,
    "image_link": "https://i.postimg.cc/DyvBZ9HY/sofa-grande2.png"
}


###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Potty",
    "sku": "PR505",
    "category": 7, 
    "description": "Minimalist flower pot",
    "large_description": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nec velit vitae urna hendrerit tempus. Sed at metus convallis, elementum dolor sed, consectetur sapien. Proin nec nulla libero. Nunc at metus pellentesque.",
    "price": 500000,
    "is_new": true,
    "image_link": "https://i.postimg.cc/3Jt9DLHr/sofa-pequeno.png"
}

